### ISSUE TITLE
ISO 20022

### ISSUE THREAD

**Issue by sdespont** [ravage84/SwissPaymentSlip#22]
Dear Marc,

Is there any plan to adapt your library with new standard ISO 20022 which include QR Code?

Best regards and thanks for your very useful work :+1:

**Comment by ravage84** [comment]
Hi @sdespont ,

There is no clear plan to adopt it, but I was aware of it "going on" and certainly I'm very open to it.

At the moment, I have no need to implement it (no related customer work).
Would you be interested to work on it?

For sure there would be many others interested into it.

Happy easter!

**Comment by ravage84** [comment]
Hi @sdespont we probably need to update the library for the new standard ISO 20022 during this year.

**Comment by sdespont** [comment]
Hello @ravage84,

Implement a standard is not an easy task. This library https://github.com/sprain/php-swiss-qr-bill has been designed for this purpose and has progressed well during theses last months. Instead of adapting your library, I would contribute on the php sprain library if needed.

**Comment by ravage84** [comment]
I'm not going to implement or action this, anymore, as this package has become obsolete due to the introduction of the [Swiss QR code payment slip](https://de.wikipedia.org/wiki/QR-Rechnung) and the discontinuation of the old ESR.

One can use https://github.com/sprain/php-swiss-qr-bill for the new Swiss QR  bill.

**Comment by ravage84** [comment]
@sdespont thank you very much for your various contributions to this project and its repos, even though I was not able to implement or action some of them.
