### ISSUE TITLE
Problem with cents values from 995 to 999

### ISSUE THREAD

**Issue by sdespont** [ravage84/SwissPaymentSlip#31]
In case of the amount is 114.9984, the result is 114 francs and 100 cents instead of 115 francs 0 cent.

https://github.com/ravage84/SwissPaymentSlip/commit/1037ca07997c46d4c4053d73dc58935c7c7c7e83

**Comment by ravage84** [comment]
Thanks for reporting. Wouldn't it be easier to round first, then split?

**Comment by sdespont** [comment]
Yes it would, but the as the amount is not always a `float`, the type must be checked before :
 ```
    // Fix case where cents are from 995 to 999 : the amount must be rounded
    // otherwise the amount of cents is "100"
    if(is_numeric($amount)) {
        $this->amount = round($amount, 2);
    } else {
        $this->amount = $amount;
    }
```

**Comment by ravage84** [comment]
Problem can also arise from summing up floats:

https://3v4l.org/4Bhe2
