### ISSUE TITLE
Formatting Individual Recipient Data Lines

### ISSUE THREAD

**Issue by frederickjh** [ravage84/SwissPaymentSlip#38]
Hi!
First of Marc Würth thanks for your hard work on this and the other Swiss Payment Slip PHP classes.
I am guessing from the todo on [line 57 of PaymentSlipData.php](https://github.com/ravage84/SwissPaymentSlip/blob/239205a87ae43b41fd2278809e6a20e1848df1d6/src/PaymentSlipData.php#L57):

>  * @todo Create a getRecipientData with formatting parameter, e.g. stripping blank lines

that there is currently no way to format individual lines of the RecipientData.

I found the public functions:
setRecipientLeftAttr()
getRecipientLeftAttr()
setRecipientRightAttr()
getRecipientRightAttr()

However it appears they set the same attributes for the Left or Right printings of the Recipient Data. I am guessing that new functions that allow setting the attributes on a per line bases would need to be added to do this.

My use case is the company name on line one of the recipient data lines is in a different font from the default and the company slogan on line two is in another different font from the default.

In any case just wanted to confirm that I was understanding this correctly.
God Bless!
Frederick

**Comment by ravage84** [comment]
Hey @frederickjh,

Yes, you are right. This is not possible right now.
We had similar needs for our mentioned customer application, so we extended my library classes where necessary.
It should be quite easy to do.
I simply never got around to document an example.

If you need help, get in touch with me by email/skype (same address).

**Comment by frederickjh** [comment]
@ravage84 Thanks! I will be in touch if  I need further help.
