### ISSUE TITLE
Support clarification

### ISSUE THREAD

**Issue by frederickjh** [ravage84/SwissPaymentSlip#39]
Hi Marc Würth!
Just a clarification. The readme document says about using the library to produce Einzahlungsschein as PDFs.
Have you ever used the library to print on pre-printed Einzahlungsschein?

Using `setSlipBackground(null);` it is possible to print without a background. Just wondering how accurate it is in filling the fields on a pre-printed Einzahlungsschein.

Thanks in advance for any advice you can give!
Frederick

**Comment by ravage84** [comment]
> The readme document says about using the library to produce Einzahlungsschein as PDFs.
Have you ever used the library to print on pre-printed Einzahlungsschein?

Yes, we use my library in an extended way in one of our customer applications to print thousands of ESRs on preprinted sheets.

> Using `setSlipBackground(null);` it is possible to print without a background. Just wondering how accurate it is in filling the fields on a pre-printed Einzahlungsschein.

If the positioning is not correct, you can adjust it by setting the x and y positions of the various elements or the whole ESR area, though it should not be necessary.
It's actually not THAT important how exact the positiong is as long as all the data is mor or less where it should be AND the ESR code line is in the correct font (OCR-B).
